import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/captiongrit-refund")({
  head: () => ({
    meta: [
      { title: "Refund Policy | CaptionGrit" },
      { name: "description", content: "Refund Policy for CaptionGrit by Flogrit" },
    ],
  }),
  component: CaptiongritRefund,
});

function CaptiongritRefund() {
  return (
    <div className="captiongrit-container min-h-screen bg-black text-white py-20 px-6 sm:px-12 font-sans">
      <div className="max-w-4xl mx-auto space-y-8">
        <Link to="/captiongrit" className="text-gray-400 hover:text-white transition-colors">
          &larr; Back to CaptionGrit
        </Link>
        <h1 className="text-4xl md:text-5xl font-display font-bold tracking-tight mb-8">
          Refund Policy
        </h1>
        <div className="space-y-6 text-gray-300 leading-relaxed">
          <p className="text-sm text-gray-500">Last updated: July 12, 2026</p>
          
          <h2 className="text-3xl font-black text-white mt-12 mb-6 uppercase tracking-wider text-red-500">
            NO REFUND POLICY
          </h2>
          <p>
            CaptionGrit, operated by Flogrit, provides a digital SaaS (Software as a Service) product. Due to the nature of our service, which offers immediate and irrevocable access to our AI-powered captioning infrastructure the moment a transaction is completed, we enforce a strict no-refund policy.
          </p>
          <p>
            By choosing to subscribe to or purchase services from CaptionGrit, you explicitly acknowledge and agree to the following terms regarding your payments:
          </p>
          <ul className="list-disc pl-6 space-y-3">
            <li><strong>All sales are absolutely final.</strong> We do not offer prorated refunds, partial refunds, or full refunds under any circumstances once a charge has been successfully processed.</li>
            <li><strong>No refunds after successful payment.</strong> The moment your payment is cleared and the digital product access is granted to your account, the transaction is considered complete and non-refundable.</li>
            <li><strong>No refunds for accidental purchases.</strong> It is your responsibility to secure your account credentials and payment methods. We will not issue refunds for claims of accidental or unintended purchases.</li>
            <li><strong>No refunds for dissatisfaction with AI-generated content.</strong> Artificial intelligence outputs are probabilistic. While we strive for the highest quality, we cannot guarantee perfection. Dissatisfaction with the specific captions, style, formatting, or contextual accuracy generated by the AI does not qualify for a refund.</li>
            <li><strong>No refunds for unused subscriptions.</strong> If you purchase a subscription (e.g., monthly or annual) and fail to utilize the service or exhaust your allocated credits during that billing cycle, you are not entitled to a refund for the unused time or resources.</li>
            <li><strong>No refunds because you no longer require the service.</strong> Changes in your personal circumstances, business model, content strategy, or project cancellations do not warrant a refund for a previously purchased plan.</li>
          </ul>

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">1. Subscription Cancellation</h2>
          <p>
            CaptionGrit operates on a recurring subscription model unless you are purchasing a one-time credit pack. You have the full right and ability to cancel your subscription at any time through your user dashboard or by contacting our support team.
          </p>
          <p>
            <strong>Cancellation only prevents future renewals.</strong> When you cancel your subscription, you are stopping the system from charging you for the <em>next</em> billing cycle. Cancellation does not retroactively refund previous payments, nor does it generate a prorated refund for the remainder of your current billing cycle. You will retain full access to the features of your paid plan until the end of your current, already-paid billing period.
          </p>

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">2. Billing Errors and Discrepancies</h2>
          <p>
            While our billing is automated through secure third-party payment gateways like Razorpay, we understand that technical errors can rarely occur. If you believe there is a mathematical error on your invoice or a discrepancy in the amount you were charged versus the advertised price, you must contact us within seven (7) days of the transaction date. We will investigate the discrepancy and, if a billing error occurred on our end or our payment processor's end, we will adjust your account credit or issue a partial refund strictly for the difference in the erroneous amount.
          </p>

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">3. Duplicate Charges</h2>
          <p>
            In the rare event that a payment gateway error causes you to be charged multiple times for a single, distinct transaction (a "Duplicate Charge"), we will review this on an individual basis. To request a review for a duplicate charge, you must provide proof of the multiple charges (e.g., bank statements showing identical charges processed at the exact same timestamp). If verified as a genuine gateway anomaly, we will void and refund the duplicate, erroneous transaction.
          </p>

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">4. Unauthorized Transactions</h2>
          <p>
            If you notice an unauthorized charge from Flogrit or CaptionGrit on your credit card or bank statement, you should first secure your financial accounts and then contact us immediately. Because we employ strict verification protocols and use highly secure third-party processors, we treat claims of unauthorized transactions seriously. We cooperate fully with financial institutions and law enforcement in fraud investigations. However, resolving unauthorized transactions typically requires you to initiate a dispute or fraud claim directly with your issuing bank or credit card company.
          </p>

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">5. Failed Payments</h2>
          <p>
            If your payment method fails during a subscription renewal, your account may be temporarily suspended or downgraded to a free tier (if applicable) until the payment can be successfully processed. We do not charge late fees, but you will lose access to premium features until the outstanding balance is cleared. A failed payment does not automatically cancel your subscription; you must still formally cancel your subscription if you no longer wish to be billed in future attempts.
          </p>

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">6. Technical Support</h2>
          <p>
            We are deeply committed to ensuring our platform functions optimally. If you encounter a technical bug, a server outage, or an issue preventing you from accessing the service you paid for, please reach out to our Technical Support team immediately. While technical interruptions do not qualify for a monetary refund according to this policy, our team will work diligently to resolve the issue, and in cases of severe, prolonged outages verified by our engineering team, we may, at our sole discretion, offer complimentary account credits or extend your billing cycle to compensate for the downtime.
          </p>

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">7. Contact Information</h2>
          <p>
            If you have questions about your billing, wish to cancel your subscription, or need to report a duplicate charge, please direct your inquiries to our support team at:
            <br />
            <a href="mailto:support.flogrit@gmail.com" className="text-blue-400 hover:underline mt-2 inline-block font-semibold">support.flogrit@gmail.com</a>
          </p>
          <p className="mt-4">
            Please include your account email address and any relevant transaction IDs or invoice numbers to help us process your inquiry efficiently.
          </p>
        </div>
      </div>
    </div>
  );
}
